NOT (PRECIO == 3 OR CANTIDAD > 0)
PRECIO != 3 AND CANTIDAD <= 0

NOT (CUIDAD == GR AND CANTIDAD <=15 OR PRECIO > 50)
CIUDAD != GR OR CANTIDAD > 15 AND PRECIO <= 50

NOT (DEPARTAMENTO == "VENTAS" OR DEPARTAMENTO == "MARKETING") AND SALARIO >5000
DEPARTAMENTO != "VENTAS" AND DEPARTAMENTO != "MARKETING" AND SALARIO <= 5000

NOT (CIUDAD == GR AND NOT (CANTIDAD <=15 OR PRECIO > 50))
CIUDAD != GR OR CANTIDAD <= 15 OR PRECIO > 50 